default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: smalltalk_development

test:
  <<: *default
  database: smalltalk_test

production:
  <<: *default
  database: smalltalk_production
  username: smalltalk
  password: <%= ENV['SMALLTALK_DATABASE_PASSWORD'] %>
